CREATE TABLE IF NOT EXISTS location(
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL,
parent_id BIGINT,
order_index int NOT NULL,
 CONSTRAINT fk_location_parent
         FOREIGN KEY (parent_id)
         REFERENCES location(id),

     CONSTRAINT uq_parent_order
         UNIQUE (parent_id, order_index)
);

--                                        ROOT(1)
--                                  -                -
--                             -                         -
--                    PC-01(2)                              PC-02(3)
--                  -           -                           -       -
--              -                   -                   -               -
--           C:(4)                   D:(5)         windows(9)            users(10)
--          -      -                   -
--      -              -               -
-- Pr. files(6)     Users(7)       Backups(8)



-- ROOT - LEVEL 0
INSERT INTO location (name, parent_id, order_index)
VALUES ('ROOT', NULL, 0);

-- LEVEL 1 - Children of Root
INSERT INTO location ( name, parent_id, order_index)
VALUES
('PC-01', 1, 0),
('PC-02', 1, 1);

-- LEVEL 2 - children of PC-01
INSERT INTO location (name, parent_id, order_index)
VALUES
('C:', 2, 0),
('D:', 2, 1);

-- LEVEL 3 - children of C: (PC-01)
INSERT INTO location (name, parent_id, order_index)
VALUES
('Program Files', 4, 0),
('Users', 4, 1);

-- LEVEL 3 - child of D: (PC-01)
INSERT INTO location ( name, parent_id, order_index)
VALUES
('Backups', 5, 0);

-- LEVEL 2 - children PC-02
INSERT INTO location (name, parent_id, order_index)
VALUES
('Windows', 3, 0),
('Users', 3, 1);

